### ISSUE TITLE
Compiled for windows

### ISSUE THREAD

**Issue by arrietaeguren** [fcinema/standalone-intf#9]

**Comment by PabloJabat** [comment]
Compilation failed with error:

QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:

**Comment by arrietaeguren** [comment]
OpenGL seems to give some problems if graphic card is not up to date and ANGLE seems not to work properly on XP: http://wiki.qt.io/Qt-5-on-Windows-ANGLE-and-OpenGL

Best option seems to use Mesa, which is suppose to run from XP on. It is slower (guess no hardware acceleration) but for our purpose it doesn't matter. http://stackoverflow.com/q/27704529/3766869

So, just add QT_OPENGL=software as environmental variable (Projects->Build Enviroment->Details->Add) and copy the opengl32.dll in the same folder as the executable. Download library from here: http://downloads.sourceforge.net/project/msys2/REPOS/MINGW/i686/mingw-w64-i686-mesa-10.0.2-1-any.pkg.tar.xz. Or read this: http://wiki.qt.io/Cross-compiling-Mesa-for-Windows

**Comment by arrietaeguren** [comment]
Maybe it's also useful to read http://wiki.qt.io/Deploy_an_Application_on_Windows
